#####################################
## Motion sensors.                 ##
#####################################

# LightLevel 1 - Movement during day.
#   -> Turn ON Bathroom lights (Brightness 200).
- alias: Turn on bathroom lights on move during day
  trigger:
    - entity_id: binary_sensor.lightlevel_1
      from: 'off'
      platform: state
      to: 'on'
  condition:
    - condition: time
      after: '08:30:00'
      before: '01:00:00'
  action:
    - service: homeassistant.turn_on
      data_template:
        entity_id: group.bathroom_lights
        brightness: 200

# LightLevel 1 - Movement during night.
#   -> Turn ON Bathroom lights (Brightness 50).
- alias: Turn on bathroom lights on move during night
  trigger:
    - entity_id: binary_sensor.lightlevel_1
      from: 'off'
      platform: state
      to: 'on'
  condition:
    - condition: time
      after: '01:00:00'
      before: '08:30:00'
  action:
    - service: homeassistant.turn_on
      data_template:
        entity_id: light.bathroom_1
        brightness: 50

# LightLevel 1 - No movement during 10 minutes.
#   -> Turn OFF Bathroom lights.
- alias: Turn off bathroom lights 10 minutes after last movement
  trigger:
    entity_id: binary_sensor.lightlevel_1
    platform: state
    to: 'off'
    for:
      minutes: 10
  action:
    - service: homeassistant.turn_off
      entity_id: group.bathroom_lights

# LightLevel 1 - No movement during 24 hours.
#   -> Set home in sleep mode.
- alias: Set home in sleep mode 24 hours after last movement
  trigger:
    entity_id: binary_sensor.lightlevel_1
    platform: state
    to: 'off'
    for:
      hours: 24
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.home_awake


#####################################
## Door sensors.                   ##
#####################################

# Door 1 - Open.
#   -> Turn ON Entrance lights for 2 minutes.
#      AND Set home in awake mode.
- alias: Turn on entrance lights on door open
  trigger:
    - platform: state
      entity_id: binary_sensor.door_1
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: group.entrance_lights
      state: 'off' 
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.home_awake
    - service: homeassistant.turn_on
      data_template:
        entity_id: group.entrance_lights
        brightness: 200
    - delay: '00:02:00'
    - service: homeassistant.turn_off
      entity_id: group.entrance_lights


#####################################
## Switches.                       ##
#####################################

# Switch 1 - Simple click.
#   -> Turn OFF Home lights.
- alias: Home off on switch click
  trigger:
    - event_data:
        event: 1002
        id: switch_1
      event_type: deconz_event
      platform: event
  condition: []
  action:
    - service: script.home_off

# Switch 2 - Simple click.
#   -> Turn ON/OFF Desk lamp.
- alias: Desk lamp on/off on switch click
  trigger:
    - event_data:
        event: 1002
        id: switch_2
      event_type: deconz_event
      platform: event
  condition: []
  action:
    - service: switch.toggle
      data_template:
        entity_id: switch.78638353ecfabc9b4420 # Desk lamp.

# Switch 3 - Simple click.
#   -> Turn ON/OFF Entrance.
- alias: Entrance on/off on switch click
  trigger:
    - event_data:
        event: 1002
        id: switch_3
      event_type: deconz_event
      platform: event
  condition: []
  action:
    - service: homeassistant.toggle
      data_template:
        entity_id: group.entrance
        brightness: 200

# Switch 4 - Simple click.
#   -> Turn ON Kitchen lights.
- alias: Kitchen on on switch click
  trigger:
    - event_data:
        event: 1002
        id: switch_4
      event_type: deconz_event
      platform: event
  condition: []
  action:
    - service: homeassistant.turn_on
      data_template:
        entity_id: group.kitchen

# Switch 4 - Double click.
#   -> Turn OFF kitchen extractor.
- alias: Extractor off on switch double click
  trigger:
    - event_data:
        event: 1004
        id: switch_4
      event_type: deconz_event
      platform: event
  condition: []
  action:
    - service: switch.toggle
      data_template:
        entity_id: switch.056042563c71bf28403e # Extractor.

# Switch 5 - Simple click.
#   -> Turn ON/OFF Bathroom.
- alias: Bathroom on/off on switch click
  trigger:
    - event_data:
        event: 1002
        id: switch_5
      event_type: deconz_event
      platform: event
  condition: []
  action:
    - service: homeassistant.toggle
      data_template:
        entity_id: group.bathroom

# Tradfri Switch 1 - Simple click ON.
#   -> Turn ON Home.
- alias: Home on on switch ON click
  trigger:
    - event_data:
        event: 1002
        id: tradfri_switch_1
      event_type: deconz_event
      platform: event
  condition: []
  action:
    - service: script.home_on

# Tradfri Switch 1 - Simple click OFF.
#   -> Turn OFF Home.
- alias: Home off on switch OFF click
  trigger:
    - event_data:
        event: 2002
        id: tradfri_switch_1
      event_type: deconz_event
      platform: event
  condition: []
  action:
    - service: script.home_off


#####################################
## Water sensors.                  ##
#####################################

# Water 1 - Leak.
#   -> Trig water_leak script.
- alias: Trig water_leak script on kitchen water leak
  trigger:
    - entity_id: binary_sensor.water_1
      from: 'off'
      platform: state
      to: 'on'
  condition: []
  action:
    - service: script.water_leak
      data_template:
        place: 'Evier de la cuisine'


#####################################
## Trackers.                       ##
#####################################

# Rabeb is Home.
#   -> Notify Francois iPhone.
- alias: Rabeb is home
  trigger:
  - entity_id: device_tracker.iphone_de_rabeb
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - alias: ''
    data:
      message: iPhone de Rabeb connecté au Wi-Fi
      title: Rabeb est à la maison
    service: notify.ios_iphone_de_francois


#####################################
## Home awake/asleep.              ##
#####################################

# Boolean - Home is awake.
#   -> Notify.
- alias: Home awake automation
  trigger:
    - entity_id: input_boolean.home_awake
      from: 'off'
      platform: state
      to: 'on'
  condition: []
  action:
    - service: notify.all_devices
      data_template:
        title: 'Home state changed'
        message: "Awake" 

# Boolean - Home is asleep.
#   -> Notify and turn off home.
- alias: Home asleep automation
  trigger:
    - entity_id: input_boolean.home_awake
      from: 'on'
      platform: state
      to: 'off'
  condition: []
  action:
    - service: script.home_off
    - service: notify.all_devices
      data_template:
        title: 'Home state changed'
        message: "Asleep" 


#####################################
## Lights depending on daytime.    ##
#####################################

# Sun - Sunset.
#   -> Turn on home lights.
# https://www.home-assistant.io/cookbook/automation_sun/
- alias: Turn on home lights at sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  condition:
    - condition: state
      entity_id: input_boolean.home_awake
      state: 'on'
  action:
    - service: script.smooth_home_on

# Time - 22:00.
#   -> Start to decrease home brightness smoothly until 23:00.
# Good to know: This automation is done in 3 steps because
#  transition mechanism does not handle a value like 10800.
# https://www.home-assistant.io/docs/automation/trigger/
- alias: Turn off home lights at night 1
  trigger:
    platform: time
    at: "22:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.home_awake
      state: 'on'
    - condition: state
      entity_id: group.living_room_lights
      state: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id:
          - group.living_room_lights
          - group.kitchen_lights
        brightness: 135
        # 3600 seconds = 1 hour.
        transition: 3600
   
# Time - 23:00.
#   -> Continue to decrease home brightness smoothly
#      until 00:00.
- alias: Turn off home lights at night 2
  trigger:
    platform: time
    at: "23:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.home_awake
      state: 'on'
    - condition: state
      entity_id: group.living_room_lights
      state: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id:
          - group.living_room_lights
          - group.kitchen_lights
        brightness: 67
        # 3600 seconds = 1 hour.
        transition: 3600

# Time - 00:00.
#   -> Continue to decrease home brightness smoothly
#      until 01:00.
- alias: Turn off home lights at night 3
  trigger:
    platform: time
    at: "00:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.home_awake
      state: 'on'
    - condition: state
      entity_id: group.living_room_lights
      state: 'on'
  action:
    - service: light.turn_on
      data_template: 
        entity_id:
          - group.living_room_lights
          - group.kitchen_lights
        brightness: 1
        # 3600 seconds = 1 hour.
        transition: 3600


#####################################
## CO2.                            ##
#####################################

# CO2 - High (Over 1000)
#   -> Trig fast_scan effect on tv ledstrip.
- alias: Trig an effect on tv ledstrip when CO2 is above 1000
  trigger:
    platform: numeric_state
    entity_id: sensor.netatmo_weather_indoor_co2
    above: 1000
    below: 1500
  condition:
    - condition: state
      entity_id: light.tv_ledstrip
      state: 'on'
  action:
    - service: light.turn_on
      data_template: 
        entity_id: light.tv_ledstrip
        effect: 'fast_scan'
    - delay:
        seconds: 15
    - service: light.turn_on
      data_template:
        entity_id: light.tv_ledstrip
        effect: 'None'
    

#####################################
## Weather.                        ##
#####################################

# Weather - Raining today?
#   -> Turn on/off cloud light at 07:00.
- alias: Turn on cloud light if it will rain today
  trigger:
    platform: time
    at: "07:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.home_awake
      state: 'on'
  action:
    - service_template:
        "{% if is_state('sensor.rain_today', 'true') %}\
          switch.turn_on\
        {% else %}\
          switch.turn_off\
        {% endif %}"
      entity_id:
        - switch.78638353ecfabc96c763 # Cloud.


#####################################
## Laundry machine.                ##
#####################################

# Door 3 - Closed.
#   -> Start laundry machine timer.
#      AND start orange_wipe_95min effect on led strip.
- alias: Start laundry machine timer on door closed
  trigger:
    - platform: state
      entity_id: binary_sensor.door_3
      from: 'on'
      to: 'off'
  action:
    - service: timer.start
      entity_id: timer.laundry_machine
    - service: light.turn_off
      data_template:
        entity_id: light.tv_ledstrip
    - service: light.turn_on
      data_template:
        entity_id: light.tv_ledstrip
        effect: 'blue_wipe_95min'

# Door 3 - Open.
#   -> Cancel laundry machine timer.
- alias: Cancel laundry machine timer on door open
  trigger:
    - platform: state
      entity_id: binary_sensor.door_3
      from: 'off'
      to: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.laundry_machine
    - service: light.turn_on
      data_template:
        entity_id: light.tv_ledstrip
        effect: 'None'

# Timer - Laundry machine run out.
#   -> Notify.
- alias: Notify when laundry_machine timer finishes
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.laundry_machine
  action:
    - service: notify.all_devices
      data:
        title: 'Machine terminée!'
        message: "Il est temps de l'étendre :-)"
    - service: light.turn_on
      data_template:
        entity_id: light.tv_ledstrip
        effect: 'blue_strobe'


#####################################
## TV automations.                 ##
#####################################

# LG TV - Turn on.
#   -> Turn on tv ledstrip.
- alias: Turn on tv ledstrip on tv start
  trigger:
    - entity_id: media_player.lg_tv
      from: 'off'
      platform: state
      to: 'on'
  condition: []
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.tv_ledstrip
        brightness: 200
        rgb_color:
          - 255
          - 190
          - 0

# LG TV - Turn off.
#   -> Turn off tv ledstrip.
# Good to know: The TV state is not really stable, so
#   we wait 20 seconds to avoid false positive.
- alias: Turn off tv ledstrip on tv stop
  trigger:
    - entity_id: media_player.lg_tv
      platform: state
      to: 'off'
      for:
        seconds: 20
  condition: []
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.tv_ledstrip


#####################################
## Cube automations.               ##
#####################################

# Xiaomi cube - Turn it.
#   -> Adjust volume of sonos system.
# Source: https://community.home-assistant.io/t/filter-out-trigger-values-rotate-xiaomi-cube/65522/17 
- id: cube volume adjust
  alias: cube_volume_adjust
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: cube_1
  condition:
    # this filters out the cube action if the middle two numbers are 0
    condition: template
    value_template: >
      {% set x = trigger.event.data.event|string %}
      {{ x|length != 4 or x[1:3] != '00' }}      
  action:
    - service: media_player.volume_set
      entity_id: media_player.salon
      data_template:
        volume_level: >
          {% if (trigger.event.data.event > 0) and (trigger.event.data.event | int < 2500) %} 
            {{ states.media_player.salon.attributes.volume_level | float + 0.1 }} 
          {% elif (trigger.event.data.event < 0) and (trigger.event.data.event | int > -2500) %} 
            {{ states.media_player.salon.attributes.volume_level | float - 0.1 }}          
          {% elif (trigger.event.data.event > 2501) and (trigger.event.data.event < 4000) %} 
            {{ states.media_player.salon.attributes.volume_level | float + 0.15 }} 
          {% elif (trigger.event.data.event < -2501) and (trigger.event.data.event | int > -4000) %} 
            {{ states.media_player.salon.attributes.volume_level | float - 0.15 }}             
          {% elif (trigger.event.data.event > 4001) and (trigger.event.data.event < 7000) %} 
            {{ states.media_player.salon.attributes.volume_level | float + 0.2 }} 
          {% elif (trigger.event.data.event < -4001) and (trigger.event.data.event | int > -7000) %} 
            {{ states.media_player.salon.attributes.volume_level | float - 0.2 }}              
          {% elif (trigger.event.data.event > 7001) and (trigger.event.data.event < 110000) %} 
            {{ states.media_player.salon.attributes.volume_level | float + 0.3 }} 
          {% elif (trigger.event.data.event < -7001) and (trigger.event.data.event | int > -110001) %} 
            {{ states.media_player.salon.attributes.volume_level | float - 0.3 }}                    
          {% elif trigger.event.data.event > 110001 %} 
            {{ states.media_player.salon.attributes.volume_level | float + 0.5 }}
          {% elif trigger.event.data.event < -110001 %} 
            {{ states.media_player.salon.attributes.volume_level | float - 0.5 }}               
          {% else %}
            {{ states.media_player.salon.attributes.volume_level | float - 0.01 }} 
          {% endif %}


#####################################
## Other automations.              ##
#####################################

# Selection - Volume.
#   -> Adjust TV Volume.
- alias: Adjust TV Volume
  trigger:
    platform: state
    entity_id: input_number.tv_volume
  condition: []
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.lg_tv
        volume_level: '{{ trigger.to_state.state | float }}'

# Selection - Channel.
#   -> Adjust TV Channel.
- alias: Adjust TV Channel
  trigger:
  - entity_id: input_select.tv_channel
    platform: state
  condition: []
  action:
    - service: media_player.select_source
      data_template:
        entity_id: media_player.lg_tv
        source: '{{ states.input_select.tv_channel.state }}'

# Selection - Light ambiance.
#   -> Adjust light ambiance.
- alias: Adjust Light Ambiance
  trigger:
    - entity_id: input_select.light_ambiance
      platform: state
  condition: []
  action:
    - service: script.turn_on
      data_template:
        entity_id: "{% if is_state(\"input_select.light_ambiance\", \"Cinema\") %}\n\
          \  script.light_ambiance_cinema\n{%-elif is_state(\"input_select.light_ambiance\"\
          , \"Cozy\") %}\n  script.light_ambiance_cozy\n{%-elif is_state(\"input_select.light_ambiance\"\
          , \"Desk Focus\") %}\n  script.light_ambiance_desk_focus\n{%-elif is_state(\"\
          input_select.light_ambiance\", \"Red\") %}\n  script.light_ambiance_red\n\
          {%-elif is_state(\"input_select.light_ambiance\", \"Sleep\") %}\n  script.home_off\n\
          {% else %}\n  none\n{% endif %}\n"
