#####################################
## Motion sensors.                 ##
#####################################

# LightLevel 1 - Movement.
#   -> Turn ON Bathroom lights.
- alias: Turn on bathroom lights on move
  trigger:
    - entity_id: binary_sensor.lightlevel_1
      from: 'off'
      platform: state
      to: 'on'
  condition: []
  action:
    - service: homeassistant.turn_on
      data: {}
      entity_id: group.bathroom_lights

# LightLevel 1 - No movement during 10 minutes.
#   -> Turn OFF Bathroom lights.
- alias: Turn off bathroom lights 10 minutes after last movement
  trigger:
    entity_id: binary_sensor.lightlevel_1
    platform: state
    to: 'off'
    for:
      minutes: 10
  action:
    service: homeassistant.turn_off
    entity_id: group.bathroom_lights


#####################################
## Door sensors.                   ##
#####################################

# OpenClose 10 - Open.
#   -> Turn ON Entrance lights for 1 minute.
- alias: Turn on entrance lights for 1 minute on door open
  trigger:
    - platform: state
      entity_id: binary_sensor.door_1
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: group.entrance_lights
      state: 'off' 
  action:
    - service: homeassistant.turn_on
      entity_id: group.entrance_lights
    - delay: '00:01:00'
    - service: homeassistant.turn_off
      entity_id: group.entrance_lights


#####################################
## Switches.                       ##
#####################################

# Switch 1 - Simple click.
#   -> Turn OFF Home lights.
- alias: Home off on switch click
  trigger:
    - event_data:
        event: 1002
        id: switch_1
      event_type: deconz_event
      platform: event
  condition: []
  action:
    - service: script.home_off

# Switch 1 - Double click.
#   -> Turn OFF Redfire.
- alias: Redfire off on switch double click
  trigger:
    - event_data:
        event: 1004
        id: switch_1
      event_type: deconz_event
      platform: event
  condition: []
  action:
    - service: script.redfire_off

# Switch 2 - Simple click.
#   -> Turn ON/OFF Desk lamp.
- alias: Desk lamp on/off on switch click
  trigger:
    - event_data:
        event: 1002
        id: switch_2
      event_type: deconz_event
      platform: event
  condition: []
  action:
    - service: switch.toggle
      data_template:
        entity_id: switch.78638353ecfabc9b4420

# Switch 3 - Simple click.
#   -> Turn ON/OFF Entrance.
- alias: Entrance on/off on switch click
  trigger:
    - event_data:
        event: 1002
        id: switch_3
      event_type: deconz_event
      platform: event
  condition: []
  action:
    - service: homeassistant.toggle
      data_template:
        entity_id: group.entrance

# Switch 4 - Simple click.
#   -> Turn ON Kitchen lights.
- alias: Kitchen on on switch click
  trigger:
    - event_data:
        event: 1002
        id: switch_4
      event_type: deconz_event
      platform: event
  condition: []
  action:
    - service: homeassistant.turn_on
      data_template:
        entity_id: group.kitchen

# Switch 4 - Double click.
#   -> Turn OFF kitchen extractor.
- alias: Extractor off on switch double click
  trigger:
    - event_data:
        event: 1004
        id: switch_4
      event_type: deconz_event
      platform: event
  condition: []
  action:
    - service: switch.toggle
      data_template:
        entity_id: switch.78638353ecfabc96c763 # Extractor.

# Switch 5 - Simple click.
#   -> Turn ON/OFF Bathroom.
- alias: Bathroom on/off on switch click
  trigger:
    - event_data:
        event: 1002
        id: switch_5
      event_type: deconz_event
      platform: event
  condition: []
  action:
    - service: homeassistant.toggle
      data_template:
        entity_id: group.bathroom

# Tradfri Switch 1 - Simple click ON.
#   -> Turn ON Home.
- alias: Home on on switch ON click
  trigger:
    - event_data:
        event: 1002
        id: tradfri_switch_1
      event_type: deconz_event
      platform: event
  condition: []
  action:
    - service: script.home_on

# Tradfri Switch 1 - Simple click OFF.
#   -> Turn OFF Home.
- alias: Home off on switch OFF click
  trigger:
    - event_data:
        event: 2002
        id: tradfri_switch_1
      event_type: deconz_event
      platform: event
  condition: []
  action:
    - service: script.home_off


#####################################
## Water sensors.                  ##
#####################################

# Water 1 - Leak.
#   -> Trig water_leak script.
- alias: Trig water_leak script on kitchen water leak
  trigger:
    - entity_id: binary_sensor.water_1
      from: 'off'
      platform: state
      to: 'on'
  condition: []
  action:
    - service: script.water_leak
      data_template:
        place: 'Evier de la cuisine'


#####################################
## Trackers.                       ##
#####################################

# Rabeb is Home.
#   -> Notify Francois iPhone.
- alias: Rabeb is home
  trigger:
  - entity_id: device_tracker.iphone_de_rabeb
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - alias: ''
    data:
      message: iPhone de Rabeb connecté au Wi-Fi
      title: Rabeb est à la maison
    service: notify.ios_iphone_de_francois


#####################################
## Other automations.              ##
#####################################

# Sun - Sunset.
#   -> Turn on home lights.
# https://www.home-assistant.io/cookbook/automation_sun/
- alias: Turn on home lights at sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
    - service: script.smooth_home_on

# Selection - Volume.
#   -> Adjust TV Volume.
- alias: Adjust TV Volume
  trigger:
    platform: state
    entity_id: input_number.tv_volume
  condition: []
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.lg_tv
        volume_level: '{{ trigger.to_state.state | float }}'

# Selection - Channel.
#   -> Adjust TV Channel.
- alias: Adjust TV Channel
  trigger:
  - entity_id: input_select.tv_channel
    platform: state
  condition: []
  action:
    - service: media_player.select_source
      data_template:
        entity_id: media_player.lg_tv
        source: '{{ states.input_select.tv_channel.state }}'

# Selection - Light ambiance.
#   -> Adjust light ambiance.
- alias: Adjust Light Ambiance
  trigger:
    - entity_id: input_select.light_ambiance
      platform: state
  condition: []
  action:
    - service: script.turn_on
      data_template:
        entity_id: "{% if is_state(\"input_select.light_ambiance\", \"Cinema\") %}\n\
          \  script.light_ambiance_cinema\n{%-elif is_state(\"input_select.light_ambiance\"\
          , \"Cozy\") %}\n  script.light_ambiance_cozy\n{%-elif is_state(\"input_select.light_ambiance\"\
          , \"Desk Focus\") %}\n  script.light_ambiance_desk_focus\n{%-elif is_state(\"\
          input_select.light_ambiance\", \"Red\") %}\n  script.light_ambiance_red\n\
          {%-elif is_state(\"input_select.light_ambiance\", \"Sleep\") %}\n  script.home_off\n\
          {% else %}\n  none\n{% endif %}\n"
