# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
 http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.241  # Add the IP address of the proxy server
#  base_url: example.duckdns.org:8123

#####################################
## Includes.                       ##
#####################################

# Frontend.
# https://www.home-assistant.io/components/frontend/
frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest

# Groups.
# https://www.home-assistant.io/components/group/
group: !include groups.yaml

# Automations.
# https://www.home-assistant.io/docs/automation/examples/
automation: !include automations.yaml

# Scripts.
# https://www.home-assistant.io/components/script/
script: !include scripts.yaml

# Customize.
# https://www.home-assistant.io/docs/configuration/customizing-devices/
homeassistant:
  customize: !include customize.yaml


#####################################
## Devices.                        ##
#####################################

sensor:
  # Home Assistant system monitor.
  # https://www.home-assistant.io/components/systemmonitor/
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: last_boot
      - type: processor_use
      - type: memory_use_percent
      - type: swap_use_percent

  # Time & Date.
  # https://www.home-assistant.io/components/time_date/
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

  # Will it rain today?
  # https://www.reddit.com/r/homeassistant/comments/bmmhhs/your_solution_to_will_it_rain_today/
  - platform: template
    sensors:
      rain_today:
        value_template:
          "{% if is_state('sensor.dark_sky_icon_0d', 'clear-day') %}\
          false\
          {% elif is_state('sensor.dark_sky_icon_0d', 'clear-night') %}\
          false\
          {% elif is_state('sensor.dark_sky_icon_0d', 'rain') %}\
          true\
          {% elif is_state('sensor.dark_sky_icon_0d', 'snow') %}\
          true\
          {% elif is_state('sensor.dark_sky_icon_0d', 'sleet') %}\
          true\
          {% elif is_state('sensor.dark_sky_icon_0d', 'wind') %}\
          false\
          {% elif is_state('sensor.dark_sky_icon_0d', 'fog') %}\
          false\
          {% elif is_state('sensor.dark_sky_icon_0d', 'cloudy') %}\
          false\
          {% elif is_state('sensor.dark_sky_icon_0d', 'partly-cloudy-day') %}\
          false\
          {% elif is_state('sensor.dark_sky_icon_0d', 'partly-cloudy-night') %}\
          false\
          {% else %}\
          false\
          {% endif %}"


#####################################
## Zones.                          ##
#####################################

# Zones.
# https://www.home-assistant.io/components/zone/
zone:
  - name: Sevenhugs
    latitude: 48.84211
    longitude: 2.321988
    radius: 100
    icon: 'mdi:worker'
  - name: Shadow
    latitude: 48.8648465
    longitude: 2.3501693
    radius: 100
    icon: 'mdi:worker'
  - name: 'EPITA'
    latitude: 48.815420
    longitude: 2.363049
    radius: 100
    icon: 'mdi:school'
  - name: 'Home'
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 100
    icon: 'mdi:home'


#####################################
## Persons.                        ##
#####################################

# Persons.
# https://www.home-assistant.io/components/person/
person:
  - name: Francois
    id: francois
    device_trackers:
      - device_tracker.iphone_13_pro
  - name: Rabeb
    id: rabeb
    device_trackers:
      - device_tracker.oneplus_a6000  # FIXME


#####################################
## Timers.                         ##
#####################################

# Timers.
# https://www.home-assistant.io/integrations/timer/
timer:
  laundry_machine:
    duration: '01:35:00'


#####################################
## Tweaks.                         ##
#####################################

# Custom switches.
switch:
  # Turn ON/OFF LG TV.
  - platform: template
    switches:
      lg_tv:
        value_template: "{{ not is_state('media_player.lg_tv', 'off') }}"
        turn_on:
          service: media_player.turn_on
          data:
            entity_id: media_player.chromecast_1
        turn_off:
          service: media_player.turn_off
          data:
            entity_id: media_player.lg_tv

# Custom selectors.
# https://www.home-assistant.io/components/input_select/
# https://www.home-assistant.io/cookbook/perform_actions_based_on_input_select/
# https://community.home-assistant.io/t/how-to-set-state-to-an-input-select/2060
input_select:
  tv_channel:
    options:
      - None
      - HDMI Switch
      - External
      - Chromecast
      - Netflix
      - YouTube
      - 'Amazon Prime Video'
    initial: None
  light_ambiance:
    options:
      - None
      - Cinema
      - Cozy
      - Desk Focus
      - Red
      - Sleep
    initial: None

# Custom number sliders.
# https://www.home-assistant.io/components/input_number/
input_number:
  tv_volume:
    initial: 0 #FIXME "{{ media_player.lg_tv.volume_level | float }}"
    min: 0
    max: 1
    step: 0.01

# Input booleans.
# https://www.home-assistant.io/integrations/input_boolean/
input_boolean:
  home_awake:
    name: Is home awake
    initial: on
