# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

#####################################
## Includes.                       ##
#####################################

# Frontend.
# https://www.home-assistant.io/components/frontend/
frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest

# Groups.
# https://www.home-assistant.io/components/group/
group: !include groups.yaml

# Automations.
# https://www.home-assistant.io/docs/automation/examples/
automation: !include automations.yaml

# Scripts.
# https://www.home-assistant.io/components/script/
script: !include scripts.yaml

# Customize.
# https://www.home-assistant.io/docs/configuration/customizing-devices/
homeassistant:
  customize: !include customize.yaml


#####################################
## Devices.                        ##
#####################################

# Hue bridge - Philips hue bulbs.
# https://www.home-assistant.io/components/hue/
hue:
  bridges:
    - host: '192.168.1.37'

# Tuya - SmartLife plugs and switches.
# https://www.home-assistant.io/components/tuya/
tuya:
  platform: smart_life
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 33

# MagicHome - Leds strip.
# https://www.home-assistant.io/components/flux_led/
light:
  - platform: flux_led
    devices:
      192.168.1.31:
        name: 'desk_leds'

# LG WebOS - Media player.
# https://www.home-assistant.io/components/webostv/
webostv:
    host: '192.168.1.60'
    name: 'lg_tv'
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret lg_tv_mac_address
    customize:
      sources:
        - 'youtube'
        - 'netflix'
        - 'PC'
        - 'Chromecast'
        - 'PS4'
        - 'HDMI Switch'

# Deconz.
# https://www.home-assistant.io/components/deconz/
# https://community.home-assistant.io/t/how-to-configure-deconz-conbee-in-docker/79149
deconz:
  host: 192.168.1.40
  port: 4043

# Google cast.
# https://www.home-assistant.io/components/cast/
cast:
  media_player:
    - host: '192.168.1.36'
    - host: '192.168.1.39'
    - host: '192.168.1.41'
    - host: '192.168.1.61'

# iOS - Notifications and tracking.
# https://www.home-assistant.io/docs/ecosystem/ios/
ios:

# Companion app.
# https://companion.home-assistant.io/docs/getting_started/getting-started
mobile_app:
discovery:

# Notify.
# https://www.home-assistant.io/integrations/notify/
notify:
  - platform: group
    name: all_devices
    services:
      - service: lg_tv
      - service: mobile_app_oneplus_a6013
      - service: mobile_app_oneplus_a6000

# Media player.
# https://www.home-assistant.io/integrations/media_player/
media_player:


#####################################
## Services.                       ##
#####################################

# Text to speech.
# https://www.home-assistant.io/components/tts/
tts:
  - platform: google_translate

sensor:
  # Home Assistant system monitor.
  # https://www.home-assistant.io/components/systemmonitor/
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: last_boot
      - type: processor_use
      - type: memory_use_percent
      - type: swap_use_percent

  # Time & Date.
  # https://www.home-assistant.io/components/time_date/
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

# Shopping list.
# https://www.home-assistant.io/components/shopping_list/
shopping_list:

# Wake on lan - For Kwak RedFire.
# https://www.home-assistant.io/components/wake_on_lan/
wake_on_lan:

# Shell commands.
shell_command:
  # To enbale it on Windows, follow method 1 of
  # https://www.wikihow.com/Remotely-Shutdown-a-Computer
  turn_off_target: !secret turn_off_redfire

# Spotify.
# https://www.home-assistant.io/integrations/spotify/
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# HACS - HA Community store.
# https://hacs.xyz/docs/installation/manual
hacs:
  token: !secret hacs_github_token

# Netatmo.
# https://www.home-assistant.io/integrations/netatmo
netatmo:
  client_id: !secret netatmo_client_id
  client_secret: !secret netatmo_client_secret


#####################################
## Zones.                          ##
#####################################

# Zones.
# https://www.home-assistant.io/components/zone/
zone:
  - name: Sevenhugs
    latitude: 48.84211
    longitude: 2.321988
    radius: 100
    icon: 'mdi:worker'
  - name: Netatmo
    latitude: 48.8298143
    longitude: 2.2395161
    radius: 100
    icon: 'mdi:worker'
  - name: 'EPITA'
    latitude: 48.815420
    longitude: 2.363049
    radius: 100
    icon: 'mdi:school'
  - name: 'Home'
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 100
    icon: 'mdi:home'


#####################################
## Devices trackers.               ##
#####################################

# Device trackers.
# https://www.home-assistant.io/components/device_tracker/
device_tracker:


#####################################
## Persons.                        ##
#####################################

# Persons.
# https://www.home-assistant.io/components/person/
person:
  - name: Francois
    id: francois
    device_trackers:
      - device_tracker.oneplus_a6013
  - name: Rabeb
    id: rabeb
    device_trackers:
      - device_tracker.oneplus_a6000


#####################################
## Tweaks.                         ##
#####################################

# Custom switches.
switch:
  # Turn ON/OFF Kwak RedFire.
  - platform: wake_on_lan
    name: 'redfire'
    mac: !secret redfire_mac_address
    host: '192.168.1.10'
    turn_off:
      - service: shell_command.turn_off_target
  # Turn ON/OFF LG TV.
  - platform: template
    switches:
      lg_tv:
        value_template: "{{ not is_state('media_player.lg_tv', 'off') }}"
        turn_on:
          service: media_player.turn_on
          data:
            entity_id: media_player.tv_du_salon
        turn_off:
          service: media_player.turn_off
          data:
            entity_id: media_player.lg_tv

# Custom selectors.
# https://www.home-assistant.io/components/input_select/
# https://www.home-assistant.io/cookbook/perform_actions_based_on_input_select/
# https://community.home-assistant.io/t/how-to-set-state-to-an-input-select/2060
input_select:
  tv_channel:
    options:
      - None
      - HDMI Switch
      - PC
      - PS4
      - Chromecast
      - Netflix
      - YouTube
      - 'Amazon Prime Video'
    initial: None
  light_ambiance:
    options:
      - None
      - Cinema
      - Cozy
      - Desk Focus
      - Red
      - Sleep
    initial: None

# Custom number sliders.
# https://www.home-assistant.io/components/input_number/
input_number:
  tv_volume:
    initial: 0 #FIXME "{{ media_player.lg_tv.volume_level | float }}"
    min: 0
    max: 1
    step: 0.01

# Input booleans.
# https://www.home-assistant.io/integrations/input_boolean/
input_boolean:
  home_awake:
    name: Is home awake
    initial: on
