esphome:
  name: esp_01
  platform: ESP8266
  board: esp01

wifi:
  ssid: "LoulouBox"
  password: "3CE2A1A26A654A71CE1F267EF273D1"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp 02 Fallback Hotspot"
    password: "CO5xephAMm96"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "q28j7!j36!$X"

ota:
  password: "q28j7!j36!$X"

light:
  - platform: binary
    name: "Blue led"
    output: gpio_2

output:
  - platform: gpio
    pin: GPIO2
    id: gpio_2